
#The story pages
[story]
	#A list of chapters
	chapters = [
	"main={#}The story{}{p}{p}You wake up from a deep sleep and discover this {4}{#}new mod{}{p}{p}After running around for a while you can see it is about telling a story!",
	"tree={#}Tree{}{p}{p}This {/}dark tree{} has a trunk and leaves. That's extremely suspicious. Almost too normal",
	"cellar={#}Cellar{}{p}{p}This dark cellar holds many secrets!{p}{i:minecraft:diamond,minecraft:emerald,minecraft:iron_ingot}{p}I wish it was {4}wine{}!",
	"k1=This is k1",
	"k2=This is k2",
	"k3=This is k3",
	"k4=This is k4",
	"k5=This is k5",
	"k6=This is k6",
	"k7=This is k7",
	"k8=This is k8",
	"k9=This is k9",
	"k10=This is k10",
	"k11=This is k11",
	"k12=This is k12",
	"k13=This is k13",
	"k14=This is k14",
	"k15=This is k15",
	"k16=This is k16"
	]
	messages = [
	"warn=This place looks {#}dangerous!{}",
	"safety=Here it is {/}safe{}"
	]

