
#The story pages
[story]
	#A list of chapters
	chapters = [
	"main={#}The story{}{p}{p}You wake up from a deep sleep and discover this {4}{#}new mod{}{p}{p}After running around for a while you can see it is about telling a story!",
	"discovered={#}Discovered{}{p}{p}Here is what we discovered so far. We {_}discovered{} if we {/}discovered{} something"
	]
	messages = [
	"warn=This place looks {#}dangerous!{}",
	"safety=Here it is {/}safe{}"
	]

